/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author Acer
 */
public class Admindashboard extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Admindashboard.class.getName());

    /**
     * Creates new form Dashboard
     */
    public Admindashboard() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        logoutt = new javax.swing.JButton();
        productss = new javax.swing.JButton();
        Orderss = new javax.swing.JButton();
        users = new javax.swing.JButton();
        adminicon = new javax.swing.JLabel();
        removee = new javax.swing.JButton();
        addproduct1 = new javax.swing.JButton();
        editt = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        Items = new javax.swing.JTable();
        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();
        jComboBox3 = new javax.swing.JComboBox<>();
        adminicon2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1399, 756));
        getContentPane().setLayout(null);

        jPanel2.setBackground(new java.awt.Color(205, 171, 171));
        jPanel2.setLayout(null);

        jPanel1.setBackground(new java.awt.Color(240, 230, 230));
        jPanel1.setLayout(null);
        jPanel1.add(jLabel1);
        jLabel1.setBounds(89, 182, 0, 0);

        jLabel5.setBackground(new java.awt.Color(0, 0, 102));
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/iconimage3.png"))); // NOI18N
        jPanel1.add(jLabel5);
        jLabel5.setBounds(57, 146, 0, 0);
        jPanel1.add(jLabel7);
        jLabel7.setBounds(20, 446, 0, 0);
        jPanel1.add(jLabel10);
        jLabel10.setBounds(243, 543, 0, 0);

        logoutt.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        logoutt.setText("Logout");
        jPanel1.add(logoutt);
        logoutt.setBounds(80, 700, 90, 24);

        productss.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        productss.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/product2.png"))); // NOI18N
        productss.setText("Products    ");
        productss.addActionListener(this::productssActionPerformed);
        jPanel1.add(productss);
        productss.setBounds(60, 220, 150, 28);

        Orderss.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        Orderss.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/orders.png"))); // NOI18N
        Orderss.setText("Orders");
        jPanel1.add(Orderss);
        Orderss.setBounds(60, 280, 150, 28);

        users.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        users.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/users.png"))); // NOI18N
        users.setText("USERS");
        users.addActionListener(this::usersActionPerformed);
        jPanel1.add(users);
        users.setBounds(60, 340, 150, 27);

        adminicon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/admin2.png"))); // NOI18N
        jPanel1.add(adminicon);
        adminicon.setBounds(100, 10, 90, 70);

        jPanel2.add(jPanel1);
        jPanel1.setBounds(0, 0, 270, 770);

        removee.setBackground(new java.awt.Color(83, 78, 153));
        removee.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        removee.setForeground(new java.awt.Color(255, 255, 255));
        removee.setText("Remove");
        jPanel2.add(removee);
        removee.setBounds(860, 200, 160, 22);

        addproduct1.setBackground(new java.awt.Color(83, 78, 153));
        addproduct1.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        addproduct1.setForeground(new java.awt.Color(255, 255, 255));
        addproduct1.setText("Add Product");
        addproduct1.addActionListener(this::addproduct1ActionPerformed);
        jPanel2.add(addproduct1);
        addproduct1.setBounds(320, 200, 180, 22);

        editt.setBackground(new java.awt.Color(83, 78, 153));
        editt.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        editt.setForeground(new java.awt.Color(255, 255, 255));
        editt.setText("EDIT");
        jPanel2.add(editt);
        editt.setBounds(590, 200, 180, 22);

        Items.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Products", "Price", "stock"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Float.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(Items);
        Items.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.MULTIPLE_INTERVAL_SELECTION);

        jPanel2.add(jScrollPane2);
        jScrollPane2.setBounds(322, 260, 710, 470);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel2.add(jComboBox1);
        jComboBox1.setBounds(332, 310, 150, 380);

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel2.add(jComboBox2);
        jComboBox2.setBounds(410, 330, 72, 220);

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel2.add(jComboBox3);
        jComboBox3.setBounds(470, 410, 72, 22);

        adminicon2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/admin.png"))); // NOI18N
        jPanel2.add(adminicon2);
        adminicon2.setBounds(1310, 0, 80, 60);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 0, 1420, 760);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void productssActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_productssActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_productssActionPerformed

    private void addproduct1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addproduct1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addproduct1ActionPerformed

    private void usersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usersActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usersActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Admindashboard().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Items;
    private javax.swing.JButton Orderss;
    private javax.swing.JButton addproduct1;
    private javax.swing.JLabel adminicon;
    private javax.swing.JLabel adminicon2;
    private javax.swing.JButton editt;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton logoutt;
    private javax.swing.JButton productss;
    private javax.swing.JButton removee;
    private javax.swing.JButton users;
    // End of variables declaration//GEN-END:variables
}
