/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author Acer
 */
public class Dashboard extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Dashboard.class.getName());

    /**
     * Creates new form Dashboard
     */
    public Dashboard() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel48 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1399, 756));
        setMinimumSize(new java.awt.Dimension(1399, 756));
        setPreferredSize(new java.awt.Dimension(1399, 756));
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(69, 64, 130));
        jPanel1.setLayout(null);

        jLabel2.setBackground(new java.awt.Color(69, 64, 130));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logo image4.0.jpg"))); // NOI18N
        jPanel1.add(jLabel2);
        jLabel2.setBounds(77, 38, 70, 66);
        jPanel1.add(jLabel1);
        jLabel1.setBounds(89, 182, 0, 0);

        jLabel5.setBackground(new java.awt.Color(0, 0, 102));
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/iconimage3.png"))); // NOI18N
        jPanel1.add(jLabel5);
        jLabel5.setBounds(57, 146, 0, 0);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Home");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(83, 146, 55, 20);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/user-3296.png"))); // NOI18N
        jPanel1.add(jLabel4);
        jLabel4.setBounds(60, 390, 24, 24);
        jPanel1.add(jLabel7);
        jLabel7.setBounds(20, 446, 0, 0);

        jLabel8.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Where old stories finds new");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(30, 440, 172, 16);

        jLabel9.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("-------closets--------");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(40, 470, 124, 17);
        jPanel1.add(jLabel10);
        jLabel10.setBounds(243, 543, 0, 0);

        jLabel11.setFont(new java.awt.Font("Segoe UI Historic", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Retro finds,Modern feels");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(20, 510, 207, 25);

        jButton4.setText("LogOut");
        jButton4.addActionListener(this::jButton4ActionPerformed);
        jPanel1.add(jButton4);
        jButton4.setBounds(76, 597, 72, 23);

        jComboBox1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "All", "Men", "Women", "Kid's", "" }));
        jComboBox1.addActionListener(this::jComboBox1ActionPerformed);
        jPanel1.add(jComboBox1);
        jComboBox1.setBounds(50, 230, 110, 30);

        jLabel48.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel48.setForeground(new java.awt.Color(255, 255, 255));
        jLabel48.setText("Section");
        jPanel1.add(jLabel48);
        jLabel48.setBounds(30, 200, 60, 20);

        jButton5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton5.setText("User");
        jPanel1.add(jButton5);
        jButton5.setBounds(100, 390, 72, 27);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(5, -1, 260, 770);

        jPanel2.setBackground(new java.awt.Color(240, 230, 230));
        jPanel2.setLayout(null);

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel12.setText("Retro Nova");
        jPanel2.add(jLabel12);
        jLabel12.setBounds(59, 6, 192, 48);

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/vertical_rounded_line2.png"))); // NOI18N
        jPanel2.add(jLabel13);
        jLabel13.setBounds(19, 6, 34, 48);

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(153, 0, 0));
        jLabel14.setText("3 Sales Found");
        jPanel2.add(jLabel14);
        jLabel14.setBounds(93, 60, 116, 25);

        jButton2.setBackground(new java.awt.Color(69, 64, 130));
        jButton2.setText("Login");
        jPanel2.add(jButton2);
        jButton2.setBounds(890, 6, 72, 23);

        jButton3.setBackground(new java.awt.Color(69, 64, 130));
        jButton3.setText("SignUp");
        jPanel2.add(jButton3);
        jButton3.setBounds(987, 6, 72, 23);

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Menshirt.png"))); // NOI18N
        jLabel15.setText("jLabel15");
        jPanel2.add(jLabel15);
        jLabel15.setBounds(6, 146, 272, 210);

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/shirt 2.jpeg"))); // NOI18N
        jPanel2.add(jLabel16);
        jLabel16.setBounds(350, 146, 225, 210);

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/tshirt m.jpeg"))); // NOI18N
        jPanel2.add(jLabel17);
        jLabel17.setBounds(608, 146, 225, 210);

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/pant.png"))); // NOI18N
        jPanel2.add(jLabel18);
        jLabel18.setBounds(50, 430, 150, 225);

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/pant m 3.jpeg"))); // NOI18N
        jPanel2.add(jLabel19);
        jLabel19.setBounds(877, 146, 197, 210);

        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/women tshirt 3.jpeg"))); // NOI18N
        jPanel2.add(jLabel22);
        jLabel22.setBounds(350, 440, 194, 192);

        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/women pant 3.0.jpg"))); // NOI18N
        jPanel2.add(jLabel23);
        jLabel23.setBounds(870, 430, 200, 200);

        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/kid tshirt 3.jpeg"))); // NOI18N
        jPanel2.add(jLabel21);
        jLabel21.setBounds(610, 430, 194, 225);

        jLabel24.setText("Type:Men shirt");
        jPanel2.add(jLabel24);
        jLabel24.setBounds(70, 360, 90, 16);

        jLabel25.setText("Price:700");
        jPanel2.add(jLabel25);
        jLabel25.setBounds(70, 380, 60, 10);

        jLabel26.setText("Quantity:1");
        jPanel2.add(jLabel26);
        jLabel26.setBounds(70, 390, 60, 16);

        jLabel27.setText("Type: Men Shirt");
        jPanel2.add(jLabel27);
        jLabel27.setBounds(410, 360, 90, 20);

        jLabel28.setText("Price:800");
        jPanel2.add(jLabel28);
        jLabel28.setBounds(410, 380, 60, 10);

        jLabel29.setText("Quantity:1");
        jPanel2.add(jLabel29);
        jLabel29.setBounds(410, 390, 70, 16);

        jLabel30.setText("Type: Kids t-shirt");
        jPanel2.add(jLabel30);
        jLabel30.setBounds(660, 360, 100, 16);

        jLabel31.setText("Price:500");
        jPanel2.add(jLabel31);
        jLabel31.setBounds(660, 380, 60, 10);

        jLabel32.setText("Quantity:1");
        jPanel2.add(jLabel32);
        jLabel32.setBounds(660, 390, 70, 16);

        jLabel33.setText("Type : kid's pant");
        jPanel2.add(jLabel33);
        jLabel33.setBounds(930, 360, 100, 16);

        jLabel34.setText("Price:600");
        jPanel2.add(jLabel34);
        jLabel34.setBounds(930, 380, 80, 10);

        jLabel35.setText("Quantity:1");
        jPanel2.add(jLabel35);
        jLabel35.setBounds(930, 390, 70, 16);

        jLabel36.setText("Type: Men pant");
        jPanel2.add(jLabel36);
        jLabel36.setBounds(80, 660, 100, 20);

        jLabel37.setText("Price:800");
        jPanel2.add(jLabel37);
        jLabel37.setBounds(80, 680, 80, 16);

        jLabel38.setText("Quantity:1");
        jPanel2.add(jLabel38);
        jLabel38.setBounds(80, 700, 70, 16);

        jLabel39.setText("Type:Female Shirt");
        jPanel2.add(jLabel39);
        jLabel39.setBounds(400, 640, 100, 20);

        jLabel40.setText("Price:650");
        jPanel2.add(jLabel40);
        jLabel40.setBounds(400, 660, 70, 16);

        jLabel41.setText("Quantity:1");
        jPanel2.add(jLabel41);
        jLabel41.setBounds(400, 680, 80, 16);

        jLabel42.setText("Type: kid's Tshirt");
        jPanel2.add(jLabel42);
        jLabel42.setBounds(660, 660, 100, 20);

        jLabel43.setText("Price:450");
        jPanel2.add(jLabel43);
        jLabel43.setBounds(660, 680, 60, 16);

        jLabel44.setText("Quantity:1");
        jPanel2.add(jLabel44);
        jLabel44.setBounds(660, 700, 55, 16);

        jLabel45.setText("Type:Women's pant");
        jPanel2.add(jLabel45);
        jLabel45.setBounds(920, 650, 110, 20);

        jLabel46.setText("Price:650");
        jPanel2.add(jLabel46);
        jLabel46.setBounds(920, 670, 70, 20);

        jLabel47.setText("Quantity :1");
        jPanel2.add(jLabel47);
        jLabel47.setBounds(920, 690, 70, 20);

        jButton1.setBackground(new java.awt.Color(51, 51, 51));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Search");
        jButton1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton1.addActionListener(this::jButton1ActionPerformed);
        jPanel2.add(jButton1);
        jButton1.setBounds(770, 70, 80, 20);
        jPanel2.add(jTextField1);
        jTextField1.setBounds(450, 60, 410, 40);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(270, 0, 1150, 760);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Dashboard().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
