/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import Controller.LoginController;
import Controller.UserController;
import java.util.List;
import javax.swing.JPanel;
import model.product;

/**
 *
 * @author Acer
 */
public class Dashboard extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Dashboard.class.getName());

    /**
     * Creates new form Dashboard
     */
    public Dashboard() {
        initComponents();
        // Set layout for Imagepanel so products display properly
        Imagepanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 15, 15));
        // Initialize the controller to load products
        new Controller.DashboardController(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Sidebarpanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        logoutbtn = new javax.swing.JButton();
        Userbtn = new javax.swing.JButton();
        Homebtn = new javax.swing.JButton();
        TopBarpanel = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        SignUpbtn = new javax.swing.JButton();
        Loginbtn = new javax.swing.JButton();
        Filter = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        Imagepanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1399, 756));
        getContentPane().setLayout(null);

        Sidebarpanel.setBackground(new java.awt.Color(69, 64, 130));
        Sidebarpanel.setLayout(null);

        jLabel2.setBackground(new java.awt.Color(69, 64, 130));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logo image4.0.jpg"))); // NOI18N
        Sidebarpanel.add(jLabel2);
        jLabel2.setBounds(77, 38, 70, 66);
        Sidebarpanel.add(jLabel1);
        jLabel1.setBounds(89, 182, 0, 0);
        Sidebarpanel.add(jLabel7);
        jLabel7.setBounds(20, 446, 0, 0);

        jLabel8.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Where old stories finds new");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(30, 440, 175, 16);
        Sidebarpanel.add(jLabel8);
        jLabel8.setBounds(10, 360, 172, 16);

        jLabel9.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("-------closets--------");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(40, 470, 118, 17);
        jPanel1.add(jLabel10);
        Sidebarpanel.add(jLabel9);
        jLabel9.setBounds(30, 380, 124, 17);
        Sidebarpanel.add(jLabel10);
        jLabel10.setBounds(243, 543, 0, 0);

        jLabel11.setFont(new java.awt.Font("Segoe UI Historic", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Retro finds,Modern feels");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(20, 510, 205, 25);
        Sidebarpanel.add(jLabel11);
        jLabel11.setBounds(0, 430, 207, 25);

        logoutbtn.setText("LogOut");
        logoutbtn.addActionListener(this::logoutbtnActionPerformed);
        Sidebarpanel.add(logoutbtn);
        logoutbtn.setBounds(70, 670, 76, 27);

        Userbtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Userbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/user-3296.png"))); // NOI18N
        Userbtn.setText("User");
        Userbtn.addActionListener(this::UserbtnActionPerformed);
        Sidebarpanel.add(Userbtn);
        Userbtn.setBounds(50, 250, 110, 35);

        Homebtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Homebtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/iconimage.png"))); // NOI18N
        Homebtn.setText("Home");
        Homebtn.setBorderPainted(false);
        Homebtn.addActionListener(this::HomebtnActionPerformed);
        Sidebarpanel.add(Homebtn);
        Homebtn.setBounds(50, 210, 110, 30);

        getContentPane().add(Sidebarpanel);
        Sidebarpanel.setBounds(5, -11, 250, 720);

        TopBarpanel.setBackground(new java.awt.Color(240, 230, 230));
        TopBarpanel.setForeground(new java.awt.Color(240, 230, 230));
        TopBarpanel.setLayout(null);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/vertical_rounded_line2.png"))); // NOI18N
        jLabel6.setText("jLabel6");
        TopBarpanel.add(jLabel6);
        jLabel6.setBounds(10, 10, 30, 70);

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel12.setText("Retro Nova");
        jPanel2.add(jLabel12);
        jLabel12.setBounds(59, 6, 192, 48);
        TopBarpanel.add(jLabel12);
        jLabel12.setBounds(40, 10, 230, 40);

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel13.setText("3 Sales Found");
        TopBarpanel.add(jLabel13);
        jLabel13.setBounds(130, 50, 120, 20);

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(153, 0, 0));
        jLabel14.setText("3 Sales Found");
        jPanel2.add(jLabel14);
        jLabel14.setBounds(93, 60, 117, 25);
        SignUpbtn.setText("SignUp");
        SignUpbtn.addActionListener(this::SignUpbtnActionPerformed);
        TopBarpanel.add(SignUpbtn);
        SignUpbtn.setBounds(880, 10, 76, 27);

        Loginbtn.setText("Login");
        Loginbtn.addActionListener(this::LoginbtnActionPerformed);
        TopBarpanel.add(Loginbtn);
        Loginbtn.setBounds(970, 10, 79, 27);

        Filter.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Filter", "Male", "Female", "Kids" }));
        TopBarpanel.add(Filter);
        Filter.setBounds(770, 10, 76, 26);

        getContentPane().add(TopBarpanel);
        TopBarpanel.setBounds(250, 0, 1150, 130);

        jScrollPane1.setPreferredSize(new java.awt.Dimension(14, 14));

        Imagepanel.setBackground(new java.awt.Color(240, 230, 230));
        jScrollPane1.setViewportView(Imagepanel);

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/pant.png"))); // NOI18N
        jPanel2.add(jLabel18);
        jLabel18.setBounds(50, 430, 150, 225);

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/pant m 3.jpeg"))); // NOI18N
        jPanel2.add(jLabel19);
        jLabel19.setBounds(877, 146, 197, 210);

        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/women tshirt 3.jpeg"))); // NOI18N
        jPanel2.add(jLabel22);
        jLabel22.setBounds(350, 440, 194, 192);

        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/women pant 3.0.jpg"))); // NOI18N
        jPanel2.add(jLabel23);
        jLabel23.setBounds(870, 430, 200, 200);

        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/kid tshirt 3.jpeg"))); // NOI18N
        jPanel2.add(jLabel21);
        jLabel21.setBounds(610, 430, 194, 225);

        jLabel24.setText("Type:Men shirt");
        jPanel2.add(jLabel24);
        jLabel24.setBounds(70, 360, 90, 16);

        jLabel25.setText("Price:700");
        jPanel2.add(jLabel25);
        jLabel25.setBounds(70, 380, 60, 10);

        jLabel26.setText("Quantity:1");
        jPanel2.add(jLabel26);
        jLabel26.setBounds(70, 390, 60, 16);

        jLabel27.setText("Type: Men Shirt");
        jPanel2.add(jLabel27);
        jLabel27.setBounds(410, 360, 90, 20);

        jLabel28.setText("Price:800");
        jPanel2.add(jLabel28);
        jLabel28.setBounds(410, 380, 60, 10);

        jLabel29.setText("Quantity:1");
        jPanel2.add(jLabel29);
        jLabel29.setBounds(410, 390, 70, 16);

        jLabel30.setText("Type: Kids t-shirt");
        jPanel2.add(jLabel30);
        jLabel30.setBounds(660, 360, 100, 16);

        jLabel31.setText("Price:500");
        jPanel2.add(jLabel31);
        jLabel31.setBounds(660, 380, 60, 10);

        jLabel32.setText("Quantity:1");
        jPanel2.add(jLabel32);
        jLabel32.setBounds(660, 390, 70, 16);

        jLabel33.setText("Type : kid's pant");
        jPanel2.add(jLabel33);
        jLabel33.setBounds(930, 360, 100, 16);

        jLabel34.setText("Price:600");
        jPanel2.add(jLabel34);
        jLabel34.setBounds(930, 380, 80, 10);

        jLabel35.setText("Quantity:1");
        jPanel2.add(jLabel35);
        jLabel35.setBounds(930, 390, 70, 16);

        jLabel36.setText("Type: Men pant");
        jPanel2.add(jLabel36);
        jLabel36.setBounds(80, 660, 100, 20);

        jLabel37.setText("Price:800");
        jPanel2.add(jLabel37);
        jLabel37.setBounds(80, 680, 80, 16);

        jLabel38.setText("Quantity:1");
        jPanel2.add(jLabel38);
        jLabel38.setBounds(80, 700, 70, 16);

        jLabel39.setText("Type:Female Shirt");
        jPanel2.add(jLabel39);
        jLabel39.setBounds(400, 640, 100, 20);

        jLabel40.setText("Price:650");
        jPanel2.add(jLabel40);
        jLabel40.setBounds(400, 660, 70, 16);

        jLabel41.setText("Quantity:1");
        jPanel2.add(jLabel41);
        jLabel41.setBounds(400, 680, 80, 16);

        jLabel42.setText("Type: kid's Tshirt");
        jPanel2.add(jLabel42);
        jLabel42.setBounds(660, 660, 100, 20);

        jLabel43.setText("Price:450");
        jPanel2.add(jLabel43);
        jLabel43.setBounds(660, 680, 60, 16);

        jLabel44.setText("Quantity:1");
        jPanel2.add(jLabel44);
        jLabel44.setBounds(660, 700, 55, 16);

        jLabel45.setText("Type:Women's pant");
        jPanel2.add(jLabel45);
        jLabel45.setBounds(920, 650, 110, 20);

        jLabel46.setText("Price:650");
        jPanel2.add(jLabel46);
        jLabel46.setBounds(920, 670, 70, 20);

        jLabel47.setText("Quantity :1");
        jPanel2.add(jLabel47);
        jLabel47.setBounds(920, 690, 70, 20);

        jButton1.setBackground(new java.awt.Color(51, 51, 51));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Search");
        jButton1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton1.addActionListener(this::jButton1ActionPerformed);
        jPanel2.add(jButton1);
        jButton1.setBounds(770, 70, 80, 20);
        jPanel2.add(jTextField1);
        jTextField1.setBounds(450, 60, 410, 40);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(270, 0, 1150, 760);
        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(260, 130, 730, 380);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SignUpbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SignUpbtnActionPerformed
        // TODO add your handling code here:
        this.dispose();
        SignUp view = new SignUp();
        UserController controller = new UserController(view);
        controller.open();
    }//GEN-LAST:event_SignUpbtnActionPerformed

    private void LoginbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginbtnActionPerformed
        // TLODO add your handling code here:
        this.dispose();
        Login view = new Login();
        LoginController controller = new LoginController(view);
        controller.open();
    }//GEN-LAST:event_LoginbtnActionPerformed

    private void HomebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HomebtnActionPerformed
            // TODO add your handling code here:
            
    }//GEN-LAST:event_HomebtnActionPerformed

    private void UserbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UserbtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UserbtnActionPerformed

    private void logoutbtnActionPerformed(java.awt.event.ActionEvent evt) {                                          
        // TODO add your handling code here:
        
    }  
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Dashboard().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> Filter;
    private javax.swing.JButton Homebtn;
    private javax.swing.JPanel Imagepanel;
    private javax.swing.JButton Loginbtn;
    private javax.swing.JPanel Sidebarpanel;
    private javax.swing.JButton SignUpbtn;
    private javax.swing.JPanel TopBarpanel;
    private javax.swing.JButton Userbtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton logoutbtn;
    // End of variables declaration//GEN-END:variables
public javax.swing.JComboBox<String> getFilter() {
    return Filter;
}

    public void displayproducts(List<product> products) {
        System.out.println("[Dashboard] displayproducts() called with " + (products != null ? products.size() : 0) + " products");
        
        Imagepanel.removeAll();
        
        if (products != null && !products.isEmpty()) {
            for (product p : products) {
                Product1 card = new Product1();
                card.setProduct(p);
                Imagepanel.add(card);
            }
            System.out.println("[Dashboard] ✓ Added " + products.size() + " product cards");
        } else {
            System.err.println("[Dashboard] ✗ No products to display");
        }
        
        Imagepanel.revalidate();
        Imagepanel.repaint();
        System.out.println("[Dashboard] ✓ Panel refreshed");
    }
    
    public void displayProducts(List<product> products) {
        displayproducts(products);  // Delegate to existing method for compatibility
    }

    public JPanel getImagePanel() {
        return Imagepanel;
    }


}
