/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.awt.event.ActionListener;

/**
 *
 * @author hp
 */
public class EmailOTP extends javax.swing.JFrame {
    private String userEmail;
    public EmailOTP(String email ){
        this.userEmail=email;
        initComponents();
    }
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(EmailOTP.class.getName());

    /**
     * Creates new form EmailOTP
     */
    public EmailOTP() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        OTP = new javax.swing.JLabel();
        OTP1 = new javax.swing.JTextField();
        resetpassword = new javax.swing.JButton();
        Resendpassword = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(240, 230, 230));

        OTP.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        OTP.setText("RECOVER YOUR ACCOUNT");

        OTP1.setBackground(new java.awt.Color(0, 0, 153));
        OTP1.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        OTP1.setForeground(new java.awt.Color(255, 255, 255));
        OTP1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        OTP1.setText("ENTER OTP");

        resetpassword.setBackground(new java.awt.Color(0, 0, 153));
        resetpassword.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        resetpassword.setForeground(new java.awt.Color(255, 255, 255));
        resetpassword.setText("Reset password");

        Resendpassword.setBackground(new java.awt.Color(0, 0, 153));
        Resendpassword.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        Resendpassword.setForeground(new java.awt.Color(255, 255, 255));
        Resendpassword.setText("Resend");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(145, 145, 145)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(resetpassword, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(OTP1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(107, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(Resendpassword)
                        .addGap(158, 158, 158))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(OTP, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(87, 87, 87))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(OTP)
                .addGap(29, 29, 29)
                .addComponent(OTP1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(resetpassword)
                .addGap(18, 18, 18)
                .addComponent(Resendpassword)
                .addContainerGap(118, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 400, 300);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new EmailOTP().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel OTP;
    private javax.swing.JTextField OTP1;
    private javax.swing.JButton Resendpassword;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton resetpassword;
    // End of variables declaration//GEN-END:variables
public String getOTP() {
        return OTP.getText().trim();
    }
    
    public String getEmail() {
        return userEmail;
    }
    
    public void addVerifyListener(ActionListener listener) {
        resetpassword.addActionListener(listener);
    }
    
    public void addResendListener(ActionListener listener) {
        Resendpassword.addActionListener(listener);
    }

}

