package view;

import java.awt.Image;
import model.product;
import javax.swing.ImageIcon;


/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

/**
 *
 * @author Acer
 */
public class ImageCard extends javax.swing.JPanel {

    /**
     * Creates new form product
     */
    
    private product pd;
    public ImageCard() {
        initComponents();
        setPreferredSize(new java.awt.Dimension(250, 300));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ImageLbl = new javax.swing.JLabel();
        Type = new javax.swing.JLabel();
        Price = new javax.swing.JLabel();

        setLayout(null);

        ImageLbl.setText("Image");
        add(ImageLbl);
        ImageLbl.setBounds(0, 0, 240, 210);

        Type.setText("Type");
        add(Type);
        Type.setBounds(20, 220, 210, 16);

        Price.setText("Price");
        add(Price);
        Price.setBounds(20, 250, 210, 16);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ImageLbl;
    private javax.swing.JLabel Price;
    private javax.swing.JLabel Type;
    // End of variables declaration//GEN-END:variables

public javax.swing.JLabel getImage() {
        return ImageLbl ;
   
}

public javax.swing.JLabel getPrice() {
   
        return Price ;
   
}

public javax.swing.JLabel getType() {
        return Type ;
   
}
    
    private product product;

    public void setProduct(product p) {
        if (p == null) {
            System.out.println("[Product1] setProduct called with null");
            return;
        }

        this.product = p;
        Type.setText(p.getType() != null ? p.getType() : "");
        Price.setText(String.format("Rs. %.2f", p.getPrice()));

        String imagePath = p.getImagePath();
        // Delegate image loading to setImage so callers can set images directly
        setImage(imagePath);
    }

    public product getProduct() {
        return this.product;
    }

    /**
     * Public method to set image by relative path (e.g. "images/Menshirt.png").
     * Uses the classloader to load resources packaged with the app.
     */
    public void setImage(String imagePath) {
        if (imagePath == null || imagePath.trim().isEmpty()) {
            System.out.println("[Product1] Image path is empty");
            ImageLbl.setIcon(null);
            ImageLbl.setText("No image");
            return;
        }

        imagePath = imagePath.replace("\\", "/").replace("\"", "").trim();
        System.out.println("[Product1] Loading: " + imagePath);

        java.awt.image.BufferedImage buf = null;

        // 1) Try classpath resource
        try {
            java.net.URL imgUrl = getClass().getClassLoader().getResource(imagePath);
            if (imgUrl != null) {
                buf = javax.imageio.ImageIO.read(imgUrl);
            }
        } catch (Exception e) {
            System.err.println("[Product1] Error reading resource: " + e.getMessage());
        }

        // 2) Try project-relative files (e.g., src/images/...) or absolute path
        if (buf == null) {
            try {
                java.io.File f1 = new java.io.File("src/" + imagePath);
                java.io.File f2 = new java.io.File(imagePath);
                if (f1.exists()) buf = javax.imageio.ImageIO.read(f1);
                else if (f2.exists()) buf = javax.imageio.ImageIO.read(f2);
            } catch (Exception e) {
                System.err.println("[Product1] Error reading file: " + e.getMessage());
            }
        }

        // 3) If found, scale and set; otherwise try fuzzy match in src/images directory
        if (buf != null) {
            try {
                int w = 180;
                int h = 160;
                java.awt.Image scaledImage = buf.getScaledInstance(w, h, java.awt.Image.SCALE_SMOOTH);
                ImageLbl.setIcon(new ImageIcon(scaledImage));
                ImageLbl.setText("");
                ImageLbl.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
                System.out.println("[Product1] ✓ Loaded: " + imagePath);
            } catch (Exception e) {
                System.err.println("[Product1] Error scaling image: " + e.getMessage());
                ImageLbl.setIcon(null);
                ImageLbl.setText("Error");
            }
        } else {
            // Try fuzzy match in src/images (ignore spaces, case, and non-alphanumeric chars)
            try {
                java.io.File imagesDir = new java.io.File("src/images");
                if (imagesDir.exists() && imagesDir.isDirectory()) {
                    String target = imagePath.substring(imagePath.lastIndexOf('/') + 1).toLowerCase().replaceAll("[^a-z0-9]", "");
                    java.io.File[] files = imagesDir.listFiles();
                    if (files != null) {
                        for (java.io.File f : files) {
                            String fname = f.getName().toLowerCase().replaceAll("[^a-z0-9]", "");
                            // 1) exact normalized match
                            if (fname.equals(target)) {
                                java.awt.image.BufferedImage fb = javax.imageio.ImageIO.read(f);
                                if (fb != null) {
                                    int w = 180;
                                    int h = 160;
                                    java.awt.Image scaledImage = fb.getScaledInstance(w, h, java.awt.Image.SCALE_SMOOTH);
                                    ImageLbl.setIcon(new ImageIcon(scaledImage));
                                    ImageLbl.setText("");
                                    ImageLbl.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
                                    System.out.println("[Product1] ✓ Fuzzy-loaded: " + f.getName());
                                    return;
                                }
                            }

                            // 2) substring match (handles 'kid tshirt 3' vs 'kidTshirt3')
                            if (fname.contains(target) || target.contains(fname)) {
                                java.awt.image.BufferedImage fb = javax.imageio.ImageIO.read(f);
                                if (fb != null) {
                                    int w = 180;
                                    int h = 160;
                                    java.awt.Image scaledImage = fb.getScaledInstance(w, h, java.awt.Image.SCALE_SMOOTH);
                                    ImageLbl.setIcon(new ImageIcon(scaledImage));
                                    ImageLbl.setText("");
                                    ImageLbl.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
                                    System.out.println("[Product1] ✓ Fuzzy-substring-loaded: " + f.getName());
                                    return;
                                }
                            }

                            // 3) compare without digits (handles womenPant30 <-> womenPant3)
                            String noDigitsTarget = target.replaceAll("[0-9]", "");
                            String noDigitsFname = fname.replaceAll("[0-9]", "");
                            if (!noDigitsTarget.isEmpty() && noDigitsTarget.equals(noDigitsFname)) {
                                java.awt.image.BufferedImage fb = javax.imageio.ImageIO.read(f);
                                if (fb != null) {
                                    int w = 180;
                                    int h = 160;
                                    java.awt.Image scaledImage = fb.getScaledInstance(w, h, java.awt.Image.SCALE_SMOOTH);
                                    ImageLbl.setIcon(new ImageIcon(scaledImage));
                                    ImageLbl.setText("");
                                    ImageLbl.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
                                    System.out.println("[Product1] ✓ Fuzzy-digits-loaded: " + f.getName());
                                    return;
                                }
                            }
                        }
                    }
                }
            } catch (Exception e) {
                System.err.println("[Product1] Error during fuzzy file search: " + e.getMessage());
            }

            System.err.println("[Product1] ✗ NOT FOUND (classpath & files): " + imagePath);
            // Create a generated placeholder so UI remains usable and persist it to src/images/ basename
            try {
                int w = 180;
                int h = 160;
                java.awt.image.BufferedImage placeholder = new java.awt.image.BufferedImage(w, h, java.awt.image.BufferedImage.TYPE_INT_RGB);
                java.awt.Graphics2D g = placeholder.createGraphics();
                g.setColor(java.awt.Color.LIGHT_GRAY);
                g.fillRect(0, 0, w, h);
                g.setColor(java.awt.Color.DARK_GRAY);
                g.setFont(new java.awt.Font("SansSerif", java.awt.Font.BOLD, 14));
                java.awt.FontMetrics fm = g.getFontMetrics();
                String text = "No Image";
                int tx = (w - fm.stringWidth(text)) / 2;
                int ty = (h - fm.getHeight()) / 2 + fm.getAscent();
                g.drawString(text, tx, ty);
                g.dispose();

                ImageLbl.setIcon(new ImageIcon(placeholder));
                ImageLbl.setText("");
                ImageLbl.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

                // Persist placeholder file to src/images/<basename> so future runs show an actual file
                try {
                    String base = imagePath.substring(imagePath.lastIndexOf('/') + 1);
                    if (base == null || base.trim().isEmpty()) base = "placeholder.jpg";
                    java.io.File outDir = new java.io.File("src/images");
                    if (!outDir.exists()) outDir.mkdirs();
                    java.io.File outFile = new java.io.File(outDir, base);
                    if (!outFile.exists()) {
                        javax.imageio.ImageIO.write(placeholder, "jpg", outFile);
                        System.out.println("[Product1] Placeholder written to: " + outFile.getAbsolutePath());
                    }
                } catch (Exception ex) {
                    System.err.println("[Product1] Failed to persist placeholder: " + ex.getMessage());
                }
            } catch (Exception e) {
                System.err.println("[Product1] Failed to create placeholder: " + e.getMessage());
                ImageLbl.setIcon(null);
                ImageLbl.setText("Not found");
            }
        }
    }

    /**
     * Attach a simple click callback to the image area.
     */
    public void setOnClick(final Runnable action) {
        // remove existing mouse listeners to avoid duplicate triggers
        java.awt.event.MouseListener[] existing = ImageLbl.getMouseListeners();
        for (java.awt.event.MouseListener m : existing) {
            ImageLbl.removeMouseListener(m);
        }

        if (action == null) return;
        ImageLbl.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                try {
                    action.run();
                } catch (Exception e) {
                    e.printStackTrace();
                }
            }
        });
    }
        
        public void loadData(product item) {
            this.pd = item;

            Type.setText(item.getType());
            Price.setText("Rs. " + item.getPrice());

            // Load image
            ImageIcon icon = new ImageIcon(item.getImagePath());
           // Image img = icon.getImage().getScaledInstance(320, 400,ImageLbl.SCALE_SMOOTH);
           Image img = icon.getImage();
            ImageLbl.setIcon(new ImageIcon(img));
        }
        
    

}