/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;
import Controller.PaymentController;
import javax.swing.*;
/**
 *
 * @author ACER
 */
public class payment1 extends javax.swing.JFrame {
    private PaymentController controller;

public payment1(PaymentController controller) {
    this.controller = controller;
}

    public payment1() {

        setTitle("Thrift Store - Make a Payment");
        setSize(450, 700);
        setLayout(null);
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        setLocationRelativeTo(null);

        JLabel title = new JLabel("THRIFT STORE");
        title.setBounds(160, 20, 200, 30);
        add(title);

        JLabel subtitle = new JLabel("Make a Payment");
        subtitle.setBounds(150, 60, 200, 30);
        add(subtitle);

        JLabel info = new JLabel("Please enter your payment information below");
        info.setBounds(100, 90, 300, 20);
        add(info);

        // ---------- Fake Card Graphic ----------
        JPanel cardPanel = new JPanel();
        cardPanel.setBounds(75, 130, 300, 180);
        cardPanel.setBorder(BorderFactory.createTitledBorder("Card"));
        add(cardPanel);

        // ---------- Text Fields ----------
        JLabel idLabel = new JLabel("ID Number");
        idLabel.setBounds(90, 330, 200, 20);
        add(idLabel);

        JTextField idField = new JTextField();
        idField.setBounds(90, 350, 250, 30);
        add(idField);

        JLabel passLabel = new JLabel("Password");
        passLabel.setBounds(90, 390, 200, 20);
        add(passLabel);

        JPasswordField passField = new JPasswordField();
        passField.setBounds(90, 410, 250, 30);
        add(passField);

        // ---------- Pay Now Button ----------
        JButton payNow = new JButton("Pay Now");
        payNow.setBounds(160, 470, 120, 35);
        add(payNow);

        payNow.addActionListener(e -> {
            JOptionPane.showMessageDialog(this, "Payment Successful!");
            dispose();
        
        });
    }
    
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setPreferredSize(new java.awt.Dimension(357, 185));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/payment.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(56, 189, -1, -1));

        jTextField1.setBackground(new java.awt.Color(153, 0, 0));
        jTextField1.setForeground(new java.awt.Color(255, 255, 255));
        jTextField1.setText("      Payment");
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(368, 28, 95, -1));

        jTextField2.setBackground(new java.awt.Color(84, 46, 122));
        jTextField2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jTextField2.setForeground(new java.awt.Color(255, 255, 255));
        jTextField2.setText("        make a payment");
        getContentPane().add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(107, 106, 235, 35));

        jLabel2.setText("please enter your payment information bellow");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(98, 155, 274, -1));

        jTextField3.setText("             Id number");
        jTextField3.addActionListener(this::jTextField3ActionPerformed);
        getContentPane().add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(154, 389, 167, -1));

        jTextField4.setText("             Password");
        jTextField4.addActionListener(this::jTextField4ActionPerformed);
        getContentPane().add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(154, 437, 167, -1));

        jButton2.setBackground(new java.awt.Color(71, 27, 115));
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Pay Now");
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(199, 489, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new payment1().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    // End of variables declaration//GEN-END:variables
class Payment {
    private String method;
    private String accountId;
    private String password;

    public String getMethod() { return method; }
    public void setMethod(String method) { this.method = method; }

    public String getAccountId() { return accountId; }
    public void setAccountId(String accountId) { this.accountId = accountId; }

    public String getPassword() { return password; }
    public void setPassword(String password) { this.password = password; }
}

}


