package view;

import model.product;
import javax.swing.ImageIcon;


/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

/**
 *
 * @author Acer
 */
public class Product1 extends javax.swing.JPanel {

    /**
     * Creates new form product
     */
    public Product1() {
        initComponents();
        setPreferredSize(new java.awt.Dimension(250, 300));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Image = new javax.swing.JLabel();
        Type = new javax.swing.JLabel();
        Price = new javax.swing.JLabel();

        setLayout(null);

        Image.setText("Image");
        add(Image);
        Image.setBounds(110, 30, 180, 160);

        Type.setText("Type");
        add(Type);
        Type.setBounds(170, 200, 26, 16);

        Price.setText("Price");
        add(Price);
        Price.setBounds(170, 230, 37, 16);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Image;
    private javax.swing.JLabel Price;
    private javax.swing.JLabel Type;
    // End of variables declaration//GEN-END:variables

public javax.swing.JLabel getImage() {
        return Image ;
   
}

public javax.swing.JLabel getPrice() {
   
        return Price ;
   
}

public javax.swing.JLabel getType() {
        return Type ;
   
}
    
    public void setProduct(product p) {
        if (p == null) {
            System.out.println("[Product1] setProduct called with null");
            return;
        }

        Type.setText(p.getType() != null ? p.getType() : "");
        Price.setText(String.format("Rs. %.2f", p.getPrice()));

        String imagePath = p.getImagePath();
        if (imagePath == null || imagePath.trim().isEmpty()) {
            System.out.println("[Product1] Image path is empty");
            Image.setIcon(null);
            Image.setText("No image");
            return;
        }

        imagePath = imagePath.replace("\\", "/").replace("\"", "").trim();
        System.out.println("[Product1] Loading: " + imagePath);
        
        java.net.URL imgUrl = getClass().getClassLoader().getResource(imagePath);
        
        if (imgUrl != null) {
            try {
                ImageIcon icon = new ImageIcon(imgUrl);
                int w = 180;
                int h = 160;
                java.awt.Image scaledImage = icon.getImage().getScaledInstance(w, h, java.awt.Image.SCALE_SMOOTH);
                Image.setIcon(new ImageIcon(scaledImage));
                Image.setText("");
                System.out.println("[Product1] ✓ Loaded: " + imagePath);
            } catch (Exception e) {
                System.err.println("[Product1] Error: " + e.getMessage());
                Image.setIcon(null);
                Image.setText("Error");
            }
        } else {
            System.err.println("[Product1] ✗ NOT FOUND: " + imagePath);
            Image.setIcon(null);
            Image.setText("Not found");
        }
    }

}