package view;


/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

/**
 *
 * @author Acer
 */
public class product extends javax.swing.JPanel {

    /**
     * Creates new form product
     */
    public product() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Image = new javax.swing.JLabel();
        Type = new javax.swing.JLabel();
        Price = new javax.swing.JLabel();

        setLayout(null);

        Image.setText("Image");
        add(Image);
        Image.setBounds(110, 30, 180, 160);

        Type.setText("Type");
        add(Type);
        Type.setBounds(170, 200, 26, 16);

        Price.setText("Price");
        add(Price);
        Price.setBounds(170, 230, 37, 16);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Image;
    private javax.swing.JLabel Price;
    private javax.swing.JLabel Type;
    // End of variables declaration//GEN-END:variables
}
