/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controller.ShippingAddressController;
import model.ShippingAddressData;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author Hp
 */
public class ShippingAddress extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ShippingAddress.class.getName());
    
    private ShippingAddressController controller = new ShippingAddressController();
    private javax.swing.JComboBox<String> addressComboBox;
    private javax.swing.JTextField addressLine1Field;
    private javax.swing.JTextField addressLine2Field;
    private javax.swing.JTextField cityField;
    private javax.swing.JTextField stateField;
    private javax.swing.JTextField zipField;
    private javax.swing.JTextField countryField;
    private javax.swing.JTextField phoneField;
    private javax.swing.JButton addButton;
    private javax.swing.JButton editButton;
    private javax.swing.JButton deleteButton;

    /**
     * Creates new form ShippingAddress
     */
    public ShippingAddress() {
        initComponents();
        initializeAddressComponents();
        loadAddresses();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(240, 230, 230));
        jPanel1.setPreferredSize(new java.awt.Dimension(719, 508));
        jPanel1.setLayout(null);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/shippingAddress.png"))); // NOI18N
        jLabel2.setText("jLabel2");
        jLabel2.setMaximumSize(new java.awt.Dimension(140, 186));
        jLabel2.setMinimumSize(new java.awt.Dimension(140, 186));
        jLabel2.setPreferredSize(new java.awt.Dimension(140, 186));
        jPanel1.add(jLabel2);
        jLabel2.setBounds(20, 80, 140, 180);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Shipping Address");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(10, 10, 160, 30);

        jPanel2.setBackground(new java.awt.Color(69, 64, 130));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("  Order Detail");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Quantity   1");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("    RS.450");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Delivery Fee:");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("RS.45");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Total : 495");

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton1.setText("Proceed to pay");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(106, 106, 106)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(43, 43, 43))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(27, 27, 27)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(99, 99, 99))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(80, 80, 80))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2);
        jPanel2.setBounds(230, 250, 310, 220);

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel10.setText("Quantity : 1");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(190, 170, 100, 30);

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel11.setText("Women's Cherry Print Tee Shirt Short");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(190, 90, 260, 20);

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel12.setText("Sleeve Crew Neck Drop Shoulder");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(190, 100, 250, 30);

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel13.setText("Vintage Tee Tops");
        jPanel1.add(jLabel13);
        jLabel13.setBounds(190, 120, 140, 20);

        jButton2.setBackground(new java.awt.Color(240, 230, 230));
        jButton2.setText("Narephant Pharmacy,koteshwor,Kathmandu");
        jPanel1.add(jButton2);
        jButton2.setBounds(10, 40, 280, 23);

        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel14.setText("   RS.450");
        jPanel1.add(jLabel14);
        jLabel14.setBounds(50, 270, 80, 20);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 679, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 530, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new ShippingAddress().setVisible(true));
    }

    private void initializeAddressComponents() {
        // Initialize components
        addressComboBox = new javax.swing.JComboBox<>();
        addressLine1Field = new javax.swing.JTextField();
        addressLine2Field = new javax.swing.JTextField();
        cityField = new javax.swing.JTextField();
        stateField = new javax.swing.JTextField();
        zipField = new javax.swing.JTextField();
        countryField = new javax.swing.JTextField();
        phoneField = new javax.swing.JTextField();
        addButton = new javax.swing.JButton("Add Address");
        editButton = new javax.swing.JButton("Edit Address");
        deleteButton = new javax.swing.JButton("Delete Address");
        
        // Set bounds (assuming null layout)
        addressComboBox.setBounds(200, 20, 300, 25);
        addressLine1Field.setBounds(200, 60, 300, 25);
        addressLine2Field.setBounds(200, 100, 300, 25);
        cityField.setBounds(200, 140, 100, 25);
        stateField.setBounds(320, 140, 100, 25);
        zipField.setBounds(440, 140, 100, 25);
        countryField.setBounds(200, 180, 150, 25);
        phoneField.setBounds(370, 180, 150, 25);
        addButton.setBounds(200, 220, 120, 30);
        editButton.setBounds(340, 220, 120, 30);
        deleteButton.setBounds(480, 220, 120, 30);
        
        // Add labels
        javax.swing.JLabel comboLabel = new javax.swing.JLabel("Select Address:");
        comboLabel.setBounds(50, 20, 150, 25);
        javax.swing.JLabel line1Label = new javax.swing.JLabel("Address Line 1:");
        line1Label.setBounds(50, 60, 150, 25);
        javax.swing.JLabel line2Label = new javax.swing.JLabel("Address Line 2:");
        line2Label.setBounds(50, 100, 150, 25);
        javax.swing.JLabel cityLabel = new javax.swing.JLabel("City:");
        cityLabel.setBounds(50, 140, 50, 25);
        javax.swing.JLabel stateLabel = new javax.swing.JLabel("State:");
        stateLabel.setBounds(310, 140, 50, 25);
        javax.swing.JLabel zipLabel = new javax.swing.JLabel("Zip:");
        zipLabel.setBounds(430, 140, 30, 25);
        javax.swing.JLabel countryLabel = new javax.swing.JLabel("Country:");
        countryLabel.setBounds(50, 180, 70, 25);
        javax.swing.JLabel phoneLabel = new javax.swing.JLabel("Phone:");
        phoneLabel.setBounds(360, 180, 50, 25);
        
        // Add to panel
        jPanel1.add(comboLabel);
        jPanel1.add(addressComboBox);
        jPanel1.add(line1Label);
        jPanel1.add(addressLine1Field);
        jPanel1.add(line2Label);
        jPanel1.add(addressLine2Field);
        jPanel1.add(cityLabel);
        jPanel1.add(cityField);
        jPanel1.add(stateLabel);
        jPanel1.add(stateField);
        jPanel1.add(zipLabel);
        jPanel1.add(zipField);
        jPanel1.add(countryLabel);
        jPanel1.add(countryField);
        jPanel1.add(phoneLabel);
        jPanel1.add(phoneField);
        jPanel1.add(addButton);
        jPanel1.add(editButton);
        jPanel1.add(deleteButton);
        
        // Add listeners
        addressComboBox.addActionListener(e -> loadSelectedAddress());
        addButton.addActionListener(e -> addAddress());
        editButton.addActionListener(e -> editAddress());
        deleteButton.addActionListener(e -> deleteAddress());
    }
    
    private void loadAddresses() {
        addressComboBox.removeAllItems();
        addressComboBox.addItem("Select an address");
        List<ShippingAddressData> addresses = controller.getAddresses();
        for (ShippingAddressData addr : addresses) {
            addressComboBox.addItem(addr.getAddressLine1() + ", " + addr.getCity());
            addressComboBox.putClientProperty(addr.getAddressLine1() + ", " + addr.getCity(), addr);
        }
    }
    
    private void loadSelectedAddress() {
        String selected = (String) addressComboBox.getSelectedItem();
        if (selected != null && !selected.equals("Select an address")) {
            ShippingAddressData addr = (ShippingAddressData) addressComboBox.getClientProperty(selected);
            if (addr != null) {
                addressLine1Field.setText(addr.getAddressLine1());
                addressLine2Field.setText(addr.getAddressLine2());
                cityField.setText(addr.getCity());
                stateField.setText(addr.getState());
                zipField.setText(addr.getZipCode());
                countryField.setText(addr.getCountry());
                phoneField.setText(addr.getPhone());
            }
        } else {
            clearFields();
        }
    }
    
    private void clearFields() {
        addressLine1Field.setText("");
        addressLine2Field.setText("");
        cityField.setText("");
        stateField.setText("");
        zipField.setText("");
        countryField.setText("");
        phoneField.setText("");
    }
    
    private void addAddress() {
        ShippingAddressData addr = new ShippingAddressData();
        addr.setAddressLine1(addressLine1Field.getText());
        addr.setAddressLine2(addressLine2Field.getText());
        addr.setCity(cityField.getText());
        addr.setState(stateField.getText());
        addr.setZipCode(zipField.getText());
        addr.setCountry(countryField.getText());
        addr.setPhone(phoneField.getText());
        
        if (controller.addAddress(addr)) {
            JOptionPane.showMessageDialog(this, "Address added successfully!");
            loadAddresses();
            clearFields();
        } else {
            JOptionPane.showMessageDialog(this, "Failed to add address. Please check all fields are filled.");
        }
    }
    
    private void editAddress() {
        String selected = (String) addressComboBox.getSelectedItem();
        if (selected != null && !selected.equals("Select an address")) {
            ShippingAddressData addr = (ShippingAddressData) addressComboBox.getClientProperty(selected);
            if (addr != null) {
                addr.setAddressLine1(addressLine1Field.getText());
                addr.setAddressLine2(addressLine2Field.getText());
                addr.setCity(cityField.getText());
                addr.setState(stateField.getText());
                addr.setZipCode(zipField.getText());
                addr.setCountry(countryField.getText());
                addr.setPhone(phoneField.getText());
                
                if (controller.updateAddress(addr)) {
                    JOptionPane.showMessageDialog(this, "Address updated successfully!");
                    loadAddresses();
                } else {
                    JOptionPane.showMessageDialog(this, "Failed to update address. Please check all fields are filled.");
                }
            }
        } else {
            JOptionPane.showMessageDialog(this, "Please select an address to edit.");
        }
    }
    
    private void deleteAddress() {
        String selected = (String) addressComboBox.getSelectedItem();
        if (selected != null && !selected.equals("Select an address")) {
            ShippingAddressData addr = (ShippingAddressData) addressComboBox.getClientProperty(selected);
            if (addr != null) {
                int confirm = JOptionPane.showConfirmDialog(this, "Are you sure you want to delete this address?", "Confirm Delete", JOptionPane.YES_NO_OPTION);
                if (confirm == JOptionPane.YES_OPTION) {
                    if (controller.deleteAddress(addr.getId())) {
                        JOptionPane.showMessageDialog(this, "Address deleted successfully!");
                        loadAddresses();
                        clearFields();
                    } else {
                        JOptionPane.showMessageDialog(this, "Failed to delete address.");
                    }
                }
            }
        } else {
            JOptionPane.showMessageDialog(this, "Please select an address to delete.");
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
